boutique_essai/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authenticate.urls')),
    path('', include('home.urls')),
    path('products/', include('store.urls')), 
]

home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home_page, name="home" ),
    path('contact/', views.contact_page, name='contact')
    
    
]

home/forms.py
from django import forms



class ContactForm(forms.Form):
    name = forms.CharField(max_length=250)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

    class Meta:
        fields = ['name', 'email', 'message']

    

home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import ContactForm
from django.contrib import messages
from django.core.mail import send_mail

# Create your views here.
def home_page(request):
    return render(request, 'home/home.html')

def contact_page(request):
    form = ContactForm()
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            title = f"Message from {name} ({email})"
            send_mail(
                title,
                message,
                "studentinstitute2024@gmail.com",
                ["studentinstitute2024@gmail.com"],
                fail_silently=False,
            )
            messages.success(
                request, "Your message has been sent successfully!")
            return redirect('contact')
    return render(request, 'home/contact.html', {'form': form})

home/templates/home/contact.html
{% extends 'base.html' %} {% load widget_tweaks %} {% block content %}
<div class="contact-page mb-5">
    <h1 class="text-center">Contact Us</h1>
    <form action="{% url 'contact' %}" method="POST" class="contact-form">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_name">Name:</label>
            {{ form.name }}
            <span class="error-message" id="nameError"></span>
        </div>
        <div class="form-group">
            <label for="id_email">Email:</label>
            {{ form.email }}
            <span class="error-message" id="emailError"></span>
        </div>
        <div class="form-group">
            <label for="id_message">Message:</label>
            {{ form.message|add_class:"text-area" }}
            <span class="error-message" id="messageError"></span>
        </div>
        <button type="submit" class="btn btn-primary btn-lg w-100">
            Submit
        </button>
    </form>
</div>
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %} {% block main_class %}homepage-main{% endblock %}
<!--ignore-prettier-->
{% block content %}
<div class="text-center">
    <div>
        <h1 class="display-3">Welcome to Boutique Alil</h1>
        <p class="lead">
            Discover the best products and unbeatable prices! Shop now and enjoy
            exclusive offers.
        </p>
        <a href="{% url 'products' %}" class="btn btn-primary btn-lg mt-3">
            Start Shopping
        </a>
    </div>
</div>
{% endblock %}